"""
run.py

Main orchestrator script for the backend of WRFrontiers Discount Visualizer.
Runs step 1 through 4.

Usage:
    python src/backend/run.py <news_url>

Example:
    python src/backend/run.py https://warrobotsfrontiers.com/en/news/272-intel-salvage-discount-event-save-big-april-14-21
"""

import argparse
import sys
from config import ITEM_NAMES_INPUT
from step1_scrape import run_step as run_step1
from step2_build_game_data import run_step as run_step2
from step3_call_gemini import run_step as run_step3
from step4_archive_gen_grid import run_step as run_step4


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run the WRFrontiers Discount Visualizer backend workflow."
    )
    parser.add_argument(
        "--items",
        dest="item_names",
        help="Comma-separated or newline-separated item names to map instead of scraping a news URL.",
    )
    parser.add_argument(
        "news_url",
        nargs="?",
        help="The War Robots: Frontiers news URL to scrape for discount items.",
    )
    parser.add_argument(
        "--date-range",
        dest="target_date_range",
        help="Optional target date range for the discount week, e.g. \"May 26 - June 2\".",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    print("Starting WRFrontiers Discount Visualizer Backend Processing...")

    # Remove any stale alternate-mode inputs before the workflow begins.
    ITEM_NAMES_INPUT.unlink(missing_ok=True)
    # If using a scraped URL, the file will be generated by step1_scrape.
    (ITEM_NAMES_INPUT.parent / "scraped_news_page.txt").unlink(missing_ok=True)

    if args.item_names:
        item_names = args.item_names.strip()
        if not item_names:
            print("Error: --items cannot be empty.")
            sys.exit(1)

        # Build game data and map the provided item names directly.
        run_step2()
        run_step3(args.target_date_range, item_names=item_names)
    else:
        if not args.news_url:
            print("Error: A news URL is required when --items is not provided.")
            sys.exit(1)

        run_step1(args.news_url)
        run_step2()
        run_step3(args.target_date_range)

    discounts = run_step4()

    print("\nDone! All steps completed successfully. Ready for frontend build.")

if __name__ == "__main__":
    main()

