name: Map

on:
  workflow_dispatch:
    inputs:
      items:
        description: Plain list of item names to map.
        required: true
        type: string
        default: ''
      target_date_range:
        description: 'Target date range (e.g. "06-16 06-23").'
        required: true
        type: string
        default: ''

permissions:
  contents: write

jobs:
  map:
    runs-on: ubuntu-latest
    env:
      DATA_REPO_PAT: ${{ secrets.DATA_REPO_PAT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Local mapping
        uses: ./.github/actions/map
        with:
          target_date_range: ${{ github.event.inputs.target_date_range }}
          items: ${{ github.event.inputs.items }}
