name: Scrape

on:
  workflow_dispatch:
    inputs:
      news_url:
        description: War Robots Frontiers news article URL
        required: true
        type: string

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Scrape and build game data
        uses: ./.github/actions/scrape
        with:
          news_url: ${{ github.event.inputs.news_url }}
